# Generated by Django 4.2.16 on 2024-12-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onevent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='event_types',
        ),
        migrations.AddField(
            model_name='upload',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='onevent.event'),
        ),
    ]
