# Generated by Django 4.2.16 on 2024-12-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onevent', '0002_remove_upload_event_types_upload_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
